-- BeparyTech Manager v1110 · SaaS / multi-azienda
-- Eseguire UNA VOLTA nel SQL Editor di Supabase.
-- IMPORTANTE: alla fine del file sostituire YOUR_USER_UUID con l'UUID del tuo account Auth.

begin;

create table if not exists public.beparytech_super_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.beparytech_companies (
  id bigint generated by default as identity primary key,
  workspace_owner_id uuid not null unique references auth.users(id) on delete restrict,
  name text not null,
  vat_number text,
  billing_email text,
  slug text unique,
  plan text not null default 'pro' check (plan in ('base','pro','business','owner')),
  status text not null default 'active' check (status in ('active','trial','suspended','expired')),
  expires_at date,
  max_users integer not null default 5 check (max_users > 0),
  max_stores integer not null default 2 check (max_stores > 0),
  modules jsonb not null default '["inventory","sales","repairs","ddt","invoicing","dymo","backup"]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists beparytech_companies_status_idx on public.beparytech_companies(status);
create index if not exists beparytech_companies_expiry_idx on public.beparytech_companies(expires_at);

create or replace function public.bt_is_super_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists(
    select 1
    from public.beparytech_super_admins s
    where s.user_id = (select auth.uid())
  );
$$;

revoke all on function public.bt_is_super_admin() from public;
revoke all on function public.bt_is_super_admin() from anon;
grant execute on function public.bt_is_super_admin() to authenticated;

alter table public.beparytech_super_admins enable row level security;
alter table public.beparytech_companies enable row level security;

-- Accesso Data API esplicito (RLS resta il controllo autorizzativo).
revoke all on table public.beparytech_super_admins from anon;
revoke all on table public.beparytech_companies from anon;
grant select on table public.beparytech_super_admins to authenticated;
grant select, insert, update, delete on table public.beparytech_companies to authenticated;
grant usage, select on sequence public.beparytech_companies_id_seq to authenticated;


drop policy if exists "superadmins_read_self" on public.beparytech_super_admins;
create policy "superadmins_read_self" on public.beparytech_super_admins
for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "superadmins_manage_companies" on public.beparytech_companies;
create policy "superadmins_manage_companies" on public.beparytech_companies
for all to authenticated
using ((select public.bt_is_super_admin()))
with check ((select public.bt_is_super_admin()));

drop policy if exists "company_members_read_own_license" on public.beparytech_companies;
create policy "company_members_read_own_license" on public.beparytech_companies
for select to authenticated
using (
  workspace_owner_id = (select auth.uid())
  or workspace_owner_id = coalesce(
      (select p.workspace_owner_id from public.beparytech_profiles p where p.user_id = (select auth.uid()) limit 1),
      (select auth.uid())
  )
  or (select public.bt_is_super_admin())
);

-- ------------------------------------------------------------
-- PASSAGGIO MANUALE OBBLIGATORIO
-- 1) Supabase > Authentication > Users
-- 2) copia il tuo UUID
-- 3) sostituiscilo qui sotto e riesegui SOLO questa INSERT
-- ------------------------------------------------------------
-- insert into public.beparytech_super_admins(user_id)
-- values ('YOUR_USER_UUID'::uuid)
-- on conflict (user_id) do nothing;

commit;
