-- BeparyTech V1.1 · Anagrafica clienti Privati / Partita IVA
-- Eseguire UNA VOLTA nel SQL Editor di Supabase.
begin;

create table if not exists public.beparytech_clients (
  id bigint generated by default as identity primary key,
  workspace_owner_id uuid not null,
  created_by uuid,
  client_type text not null default 'private' check (client_type in ('private','business')),
  display_name text not null,
  phone text,
  email text,
  tax_code text,
  vat_number text,
  recipient_code text,
  pec text,
  address text,
  zip_code text,
  city text,
  province text,
  country text not null default 'IT',
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_bt_clients_workspace_name on public.beparytech_clients(workspace_owner_id,display_name);
create index if not exists idx_bt_clients_workspace_vat on public.beparytech_clients(workspace_owner_id,vat_number) where vat_number is not null;

alter table public.beparytech_clients enable row level security;

drop policy if exists bt_clients_admin_select on public.beparytech_clients;
create policy bt_clients_admin_select on public.beparytech_clients
for select to authenticated using (
  exists (select 1 from public.beparytech_profiles p where p.user_id=auth.uid() and p.active=true and p.role='admin' and p.workspace_owner_id=beparytech_clients.workspace_owner_id)
);

drop policy if exists bt_clients_admin_insert on public.beparytech_clients;
create policy bt_clients_admin_insert on public.beparytech_clients
for insert to authenticated with check (
  created_by=auth.uid() and exists (select 1 from public.beparytech_profiles p where p.user_id=auth.uid() and p.active=true and p.role='admin' and p.workspace_owner_id=beparytech_clients.workspace_owner_id)
);

drop policy if exists bt_clients_admin_update on public.beparytech_clients;
create policy bt_clients_admin_update on public.beparytech_clients
for update to authenticated using (
  exists (select 1 from public.beparytech_profiles p where p.user_id=auth.uid() and p.active=true and p.role='admin' and p.workspace_owner_id=beparytech_clients.workspace_owner_id)
) with check (
  exists (select 1 from public.beparytech_profiles p where p.user_id=auth.uid() and p.active=true and p.role='admin' and p.workspace_owner_id=beparytech_clients.workspace_owner_id)
);

revoke all on public.beparytech_clients from anon;
revoke all on public.beparytech_clients from authenticated;
grant select,insert,update on public.beparytech_clients to authenticated;
grant usage,select on sequence public.beparytech_clients_id_seq to authenticated;

commit;
