-- BeparyTech V1.5 · Ricambi Hub + Ritiro Usato
-- Eseguire una sola volta nel SQL Editor di Supabase.
begin;

create table if not exists public.beparytech_parts (
  id bigint generated by default as identity primary key,
  workspace_owner_id uuid not null references auth.users(id) on delete cascade,
  brand text not null,
  model text not null,
  version text,
  category text not null default 'Altri Ricambi',
  name text not null,
  sku text,
  barcode text,
  supplier text,
  cost_price numeric(12,2) not null default 0,
  sale_price numeric(12,2) not null default 0,
  vat_rate numeric(5,2) not null default 22,
  quantity integer not null default 0 check(quantity>=0),
  low_stock_threshold integer not null default 2 check(low_stock_threshold>=0),
  notes text,
  active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_bt_parts_workspace on public.beparytech_parts(workspace_owner_id,brand,model,version,category);
create unique index if not exists uq_bt_parts_identity on public.beparytech_parts(workspace_owner_id,lower(brand),lower(model),lower(coalesce(version,'')),lower(category),lower(name),lower(coalesce(sku,''))) where active=true;

create table if not exists public.beparytech_used_intakes (
  id bigint generated by default as identity primary key,
  workspace_owner_id uuid not null references auth.users(id) on delete cascade,
  brand text not null, model text not null, version text, capacity text, color text,
  imei1 text not null, imei2 text, serial text,
  valuation numeric(12,2) not null default 0,
  blacklist_checked boolean not null default false,
  blacklist_result text not null default 'Da verificare' check(blacklist_result in ('Da verificare','Pulito','Segnalato')),
  blacklist_checked_at timestamptz,
  declared_not_stolen boolean not null default false,
  ownership_declared boolean not null default false,
  accounts_removed boolean not null default false,
  data_erased boolean not null default false,
  condition_accepted boolean not null default false,
  terms_accepted boolean not null default false,
  customer_name text not null,
  customer_document text,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_bt_used_workspace_created on public.beparytech_used_intakes(workspace_owner_id,created_at desc);
create index if not exists idx_bt_used_imei1 on public.beparytech_used_intakes(workspace_owner_id,imei1);

alter table public.beparytech_parts enable row level security;
alter table public.beparytech_used_intakes enable row level security;
revoke all on public.beparytech_parts, public.beparytech_used_intakes from anon;
grant select,insert,update,delete on public.beparytech_parts, public.beparytech_used_intakes to authenticated;
grant usage,select on sequence public.beparytech_parts_id_seq, public.beparytech_used_intakes_id_seq to authenticated;

drop policy if exists bt_parts_workspace_all on public.beparytech_parts;
create policy bt_parts_workspace_all on public.beparytech_parts for all to authenticated
using (workspace_owner_id = coalesce((select p.workspace_owner_id from public.beparytech_profiles p where p.user_id=(select auth.uid()) limit 1),(select auth.uid())) or (select public.bt_is_super_admin()))
with check (workspace_owner_id = coalesce((select p.workspace_owner_id from public.beparytech_profiles p where p.user_id=(select auth.uid()) limit 1),(select auth.uid())) or (select public.bt_is_super_admin()));

drop policy if exists bt_used_workspace_all on public.beparytech_used_intakes;
create policy bt_used_workspace_all on public.beparytech_used_intakes for all to authenticated
using (workspace_owner_id = coalesce((select p.workspace_owner_id from public.beparytech_profiles p where p.user_id=(select auth.uid()) limit 1),(select auth.uid())) or (select public.bt_is_super_admin()))
with check (workspace_owner_id = coalesce((select p.workspace_owner_id from public.beparytech_profiles p where p.user_id=(select auth.uid()) limit 1),(select auth.uid())) or (select public.bt_is_super_admin()));

-- abilita Realtime per le due nuove tabelle, senza fallire se già presenti
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.beparytech_parts;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.beparytech_used_intakes;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
commit;
